### PR TITLE
[Merged by Bors] - Fix a panic case

### PR DESCRIPTION
**Pull request by amircodota**

### CODE REVIEW

**Review by tjtelan — CHANGES_REQUESTED** [review]
Thanks for the contribution! This is reasonable and I was able to manually verify your fix.

There's one small change in the existing tests need to be fixed

The only reason for the test failure is because it is looking for the old output. Can you update the expected text to match your new error please?
https://github.com/tjtelan/git-url-parse-rs/blob/aeae60c6f302f2ec746896968dd07f5f6d38d6a1/tests/parse.rs#L313

**Comment by jondot** [comment]
Thanks @amircodota we just bumped into this as well.
@tjtelan could you cut a new version?

**Comment by tjtelan** [comment]
> Thanks @amircodota we just bumped into this as well. @tjtelan could you cut a new version?

Yup, done

https://crates.io/crates/git-url-parse/0.4.1

**Pull request closed without merging**
